import io.restassured.http.ContentType;
import org.testng.annotations.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import io.restassured.response.Response;

/*
     * given() -> request setup (headers, body, auth, params, etc.)
     * when()  -> HTTP action (GET, POST, PUT, DELETE, PATCH)
     * then()  -> assertions and validations
     */

public class HTTPRequestsTests {

    private static final String BASE_URL = "http://localhost:3000/users";

    // Will store the ID generated by JSON Server
    private static String userId;

    @Test(priority = 1)
    public void createUser() {

        String requestBody = """
        {
            "name": "Piyush",
            "email": "piyush@example.com"
        }
        """;

        Response response =
                given()
                        .contentType(ContentType.JSON)
                        .body(requestBody)
                .when()
                        .post(BASE_URL);

        response.then()
                .statusCode(201)
                .body("name", equalTo("Piyush"))
                .body("email", equalTo("piyush@example.com"));

        // Capture generated ID
        userId = response.jsonPath().getString("id");

        System.out.println("Created User ID: " + userId);

        response.prettyPrint();
    }

    //@Test(priority = 2, dependsOnMethods = "createUser")
    public void getUsers() {

        given()
        .when()
                .get(BASE_URL)
        .then()
                .statusCode(200)
                .log().all();
    }

    //@Test(priority = 3, dependsOnMethods = "createUser")
    public void getSingleUser() {

        given()
        .when()
                .get(BASE_URL + "/" + userId)
        .then()
                .statusCode(200)
                .body("id", equalTo(userId))
                .log().all();
    }

    @Test(priority = 2, dependsOnMethods = "createUser")
    public void updateUser() {

        String requestBody = """
        {
            "id": "%s",
            "name": "Piyush Giri",
            "email": "abc.updated@example.com"
        }
        """.formatted(userId);

        given()
                .contentType(ContentType.JSON)
                .body(requestBody)
        .when()
                .put(BASE_URL + "/" + userId)
        .then()
                .statusCode(200)
                .body("name", equalTo("Piyush Giri"))
                .body("email", equalTo("abc.updated@example.com"))
                .log().all();
    }

    /*@Test(priority = 5, dependsOnMethods = "updateUser")
    public void deleteUser() {

        given()
        .when()
                .delete(BASE_URL + "/" + userId)
        .then()
                .statusCode(200)
                .log().all();
    }

    @Test(priority = 6, dependsOnMethods = "deleteUser")
    public void verifyDeletion() {

        given()
        .when()
                .get(BASE_URL + "/" + userId)
        .then()
                .statusCode(404)
                .log().all();
    }*/
}